version: "3.8"
services:
  dubbo_customer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10004:8080"
    depends_on:
      - dubbo_provider
  dubbo_provider:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "10003:8080"
